### ISSUE TITLE
Possible inconsistency between code and paper infogate mask computation

### ISSUE THREAD

**Issue by jesbu1** [manantomar/agent-centric-representations#3]
Eq. 2 in the paper states that the observation `x` is merged with random gaussian noise `epsilon`, but at line 123 in the infogating file https://github.com/manantomar/agent-centric-representations/blob/main/infogating.py#L123, it seems that the observation is mixed with an all zeros mask.

Combined with the random noise (which is actually dropped after 1000 steps in the UNet), I believe this is instead equivalent to `ig(x) + clip(N(ig(x), 0.5), ig(x) - 0.3, ig(x) + 0.3)x`.

Can you help explain the discrepancy? Which version is correct, or am I misunderstanding the code?

Thanks!

**Comment by jesbu1** [comment]
In addition, https://github.com/manantomar/agent-centric-representations/blob/main/infogating.py#L134 seems to randomly permute the inputs with the masked observations, is this specific to the implementation here or was this performed for all tasks and downstream objective?

**Comment by manantomar** [comment]
Hi! 

- Both zero masking and Gaussian masking seemed to work the same in the MuJoCo cases and hence we stuck with the zero masking version simply because it produced clearer visualizations as to what is masked and what is not. The technically 'correct' version is the Gaussian one but I doubt you will find much difference in performance between the two. The Gaussian one might be better suited for being robust to different kinds of irrelevant information depending on the domain.

- For the mixed sampling, we used this for all tasks and downstream objectives. This is detailed out in the last ablations section in the paper (page 9 of the Arxiv version). The main rationale here being that we do not want the downstream objective to be sensitive to a particular masking strategy. With mixing of the original and masked inputs, we can throw out the masking net entirely at evaluation time.

Hope this clarifies things!

**Comment by jesbu1** [comment]
This is super helpful, thanks!

**Comment by jesbu1** [comment]
One more question: you stated that the zero and gaussian masking worked the same in Mujoco cases, i'm assuming this refers to Mujoco locomotion tasks?

I wanted to incorporate this pipeline into a method for manipulation tasks, what was your experience with these design choices in, e.g., Franka Kitchen?

**Comment by manantomar** [comment]
I think they should work similarly in general, just because the zero masking is a special case of Gaussian masking, i.e. there is information loss in both cases. So you should be fine when running this on Franka kitchen as well. But feel free to reopen this issue if you face any problems!
